name: Comment

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    paths:
      - '.github/workflows/**'
      - 'WORKFLOW/**'

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scratchattach
        python -m pip install PyGithub

    - name: Run Python Script
      run: python WORKFLOW/comment.py
      env:
        QUESTLORD_PASSWORD: ${{ secrets.QUESTLORD_PASSWORD }}
        QUESTLORD_USERNAME: ${{ secrets.QUESTLORD_USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
